services:
    userbundle.tblprefix_subscriber:
        class: Sample\UserBundle\Subscriber\TablePrefixSubscriber
        arguments: [%samplebundle.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
