security:
    acl:
        connection: default

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Sample\UserBundle\Entity\User:
            algorithm:           sha512
            encode_as_base64:    true
            iterations:          5000

    role_hierarchy:
        ROLE_USER:              [ROLE_USER]
        ROLE_ADMIN:             [ROLE_USER]
        ROLE_SUPER_ADMIN:       [ROLE_USER, ROLE_ADMIN]

    providers:
        user_db:
            entity: { class: Sample\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        app_area:
            pattern:  ^/app/*
            security: false
        login:
            pattern:  ^/$
            security: false
        sugnup_form:
            pattern:  ^/account/sugnup
            security: false
        secured_area:
            pattern:    ^/
            form_login:
                check_path: _security_check
                login_path: _login
                use_forward: false
                use_referer: true
            logout:
                path:   logout
                target: _login

        main:
            anonymous: ~
