services:
    yahoofinancebundle.tblprefix_subscriber:
        class: Sample\YahooFinanceBundle\Subscriber\TablePrefixSubscriber
        arguments: [%samplebundle.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
